apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployCurrencyAppDevopsSchool
  labels:
    app: currencyAppDevopsSchool
    owner: p.solovev
spec:
  selector:
    matchLabels:
      app: currencyAppDevopsSchool
  replicas: 2
  template:
    metadata:
      labels:
        app: currencyAppDevopsSchool
    spec:
      containers:
      - name: currencyAppDevopsSchool
        image: malinkamedok/currency_app:stable
        ports:
        - containerPort: 8000
        env:
        - name: VERSION
          value: "0.3.0"
        - name: PORT
          value: 8000
