apiVersion: v1
kind: Service
metadata:
  name: serviceCurrencyAppDevopsSchool
  labels:
    run: currencyAppDevopsSchool
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: currencyAppDevopsSchool
