default:
  tags:
    - common

include:
  - project: devops-school-2024/ci
    ref: main
    file: test-bare-app.yml

lint:
  image: ghcr.io/malinkamedok/docker-image-go-lint:latest
  stage: test
  script:
    - golangci-lint run

lint:commit:
  image:
    name: registry.hub.docker.com/commitlint/commitlint:latest
    entrypoint: ['']
  stage: test
  script:
    - echo "${CI_COMMIT_MESSAGE}" | commitlint
