default:
  tags:
    - common

include:
  - remote: 'https://gitlab.com/yesolutions/gitlab-ci-templates/raw/main/templates/pre-commit-autofix.yaml'

variables:
  PRE_COMMIT_DEDUPLICATE_MR_AND_BRANCH: "false"
  PRE_COMMIT_AUTO_FIX_BRANCH_ONLY: "true"

lint:
  image: ghcr.io/malinkamedok/docker-image-go-lint:latest
  stage: test
  script:
    - golangci-lint run

lint:commit:
  image:
    name: registry.hub.docker.com/commitlint/commitlint:latest
    entrypoint: ['']
  stage: test
  script:
    - echo "${CI_COMMIT_MESSAGE}" | commitlint
