---
# tasks file for crio

- name: Ensure necessary packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - ca-certificates
    - curl
    - gpg

- name: Ensure keyrings dir exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0o755"
    owner: root
    group: root

- name: Add official GPG key
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/addons:/cri-o:/{{ crio_project_path }}/deb/Release.key"
    state: present
    keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg

- name: Add CRI-O apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/{{ crio_project_path }}/deb/ /"
    state: present
    filename: cri-o

- name: Ensure CRI-O package is installed
  ansible.builtin.apt:
    name: cri-o={{ crio_kubernetes_version }}*
    state: present
    update_cache: true
    cache_valid_time: 0
    clean: true

- name: Ensure CRI-O service is started
  ansible.builtin.service:
    name: crio
    state: started
    enabled: true

- name: Check if swap is enabled
  ansible.builtin.command:
    cmd: swapon -s
  register: swap_check
  changed_when: false

- name: Ensure swap is turned off
  when: swap_check.stdout | length > 0
  block:
    - name: Ensure swap is disabled
      ansible.builtin.command:
        cmd: swapoff -a
      changed_when: true

    - name: Ensure swap is removed from fstab
      ansible.builtin.lineinfile:
        path: '/etc/fstab'
        regexp: '\sswap\s'
        state: 'absent'

- name: Ensure br_netfilter module is loaded
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Ensure IP forwarding is enabled
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true
